project:
  type: website
  output-dir: build      # All HTML/PDFs go here to reduce clutter
  execute-dir: project

website:
  title: "NewsPipe Data Platform"
  sidebar:
    style: "docked"
    contents:
      - section: "Pipelines"
        contents: "notebooks/*/*.ipynb"

execute:
  enabled: true
  freeze: false


