[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "newspipe"
version = "0.1.0"
dependencies = [
    "pyspark",
    "returns",
    "pydantic",
    "dependency-injector",
    "httpx",
    "structlog",
    "aiokafka",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
newspipe-ingest = "newspipe.entrypoints.main:main"
